:doctype: article
:imagesdir: .
:icons: font

== Security Policy

- link:docs/SECURITY.zh_CN.adoc[简体中文]
- link:SECURITY.adoc[English]

== Supported Versions

[cols="1,1",options="header"]
|===
| Version | Supported
| 1.x.x   | ✅
| 2.x.x   | ✅
|===

== Reporting a Vulnerability

The mumu team and community take security bugs in mumu seriously.
We appreciate your efforts to responsibly disclose your findings, and will make every effort to acknowledge your contributions.

To report a security issue, please use the GitHub Security Advisory link:https://github.com/conifercone/mumu/security/advisories/new[Report a Vulnerability]
tab.

The mumu team will send a response indicating the next steps in handling your report.
After the initial reply to your report, the security team will keep you informed of the progress towards a fix and full announcement, and may ask for additional information or guidance.

Report security bugs in third-party modules to the person or team maintaining the module.
