-- @formatter:off
-- noinspection SqlConstantExpressionForFile
-- noinspection SqlResolveForFile
-- 修改时间和创建时间默认值修改为当前UTC时间
ALTER TABLE oauth2_registered_client ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE oauth2_registered_client ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE permission_paths ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE permission_paths ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE permissions ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE permissions ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE permissions_archived ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE permissions_archived ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE role_paths ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE role_paths ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE role_permissions ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE role_permissions ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE roles ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE roles ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE roles_archived ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE roles_archived ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_addresses ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_addresses ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_roles ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_roles ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users_archived ALTER COLUMN creation_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users_archived ALTER COLUMN modification_time SET DEFAULT CURRENT_TIMESTAMP;
