dependencies {
    implementation(project(":centaur-message:message-domain"))
    implementation(project(":centaur-message:message-client"))
    implementation(project(":centaur-unique:unique-client"))
    implementation(project(":centaur-extension"))
    implementation(libs.netty)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.protobuf.java)
    implementation(libs.spring.security.core)
    implementation(libs.jakarta.validation.api)
    implementation(libs.hypersistence.utils.hibernate63)
    implementation(libs.postgresql)
    implementation(libs.redis.om.spring)
    annotationProcessor(libs.redis.om.spring)
    annotationProcessor(libs.hibernate.jpamodelgen)
}
