### 添加存储区域
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("storage-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{storage-service-url}}/zone/add
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "code": "test",
  "name": "测试区域",
  "description": "测试用区域",
  "policy": "PUBLIC"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}
