dependencies {
    implementation(project(":centaur-authentication:authentication-domain"))
    implementation(project(":centaur-authentication:authentication-client"))
    implementation(project(":centaur-log:log-client"))
    implementation(project(":centaur-unique:unique-client"))
    implementation(project(":centaur-extension"))
    annotationProcessor(project(":centaur-processor"))
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.protobuf.java)
    implementation(libs.spring.security.core)
    implementation(libs.spring.security.crypto)
    implementation(libs.jakarta.validation.api)
    implementation(libs.hypersistence.utils.hibernate63)
    implementation(libs.postgresql)
    implementation(libs.redis.om.spring)
    annotationProcessor(libs.redis.om.spring)
    annotationProcessor(libs.hibernate.jpamodelgen)
}
