#!/bin/sh

# 获取所有被暂存的文件
changed_files=$(git diff --cached --name-only)

# 过滤出 Java、Kotlin文件
java_files=$(echo "$changed_files" | grep '\.java$')
kotlin_files=$(echo "$changed_files" | grep '\.kt$')

# 初始化标志
update_license_needed=0

# 检查是否需要检查license
if [ ! -z "$java_files" ]; then
    update_license_needed=1
fi

# 检查是否需要检查license
if [ ! -z "$kotlin_files" ]; then
    update_license_needed=1
fi

# 如果没有文件需要检查，直接退出
if [ [ $update_license_needed -eq 0 ]; then
    echo "☀️ No relevant files changed, skipping Update license."
    exit 0
fi

if [ $update_license_needed -eq 1 ]; then
  echo "🦉 Running Update license on changed Java or Kotlin files..."
  # 执行update_license脚本
  ./update_license.sh
  # 暂存变更
  git add .
  echo "🎉 License updated."
fi
