### 注册账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/register
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*

{
  "username": "test_2",
  "password": "test_2",
  "roleCodes": [
    "test",
    "admin"
  ],
  "avatarUrl": "https://github.com/users/conifercone",
  "phone": "{{$random.phoneNumber.phoneNumber}}",
  "sex": "MALE",
  "email": "{{$random.email}}",
  "timezone": "Asia/Shanghai",
  "language": "EN",
  "birthday": "1995-08-02",
  "addresses": [
    {
      "street": "历城区",
      "city": "济南市",
      "state": "山东省",
      "postalCode": "250000",
      "country": "中国"
    },
    {
      "street": "历下区",
      "city": "济南市",
      "state": "山东省",
      "postalCode": "250000",
      "country": "中国"
    }
  ],
  "captchaId": 127267766272,
  "captcha": "U4BC"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 根据ID修改账户基本信息
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/updateById
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "id": 1,
  "bio": "不想把这个世界交给无趣的人"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 分页获取账户（不查询总数）
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/account/findAllSlice?current=1&pageSize=10&username=admin
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 账户添加地址
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/addAddress
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "country": "中国",
  "state": "山东省",
  "city": "济南市",
  "street": "历城区",
  "postalCode": "250000",
  "location": {
    "x": 117.18689,
    "y": 36.65065
  }
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 更新账户角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/updateRoleById
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "id": 1,
  "roleCodes": [
    "admin"
  ]
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 重置当前账户系统设置
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/resetSystemSettingsBySettingsId/601146283917317
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 当前账户添加系统设置
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/addSystemSettings
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "profile": "default",
  "name": "默认系统设置",
  "enabled": true
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 通过设置id修改系统设置
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/modifySystemSettingsBySettingsId
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "id": "601146283917317",
  "name": "默认系统设置"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 禁用账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/disable/1
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 删除当前账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
DELETE {{authentication-service-url}}/account/deleteCurrent
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "captchaId": 2977796456448,
  "captcha": "ZGYW"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 重置密码
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/resetPassword/1
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 获取当前登录账户信息
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/account/currentLoginAccount
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 分页查询账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/account/findAll?current=1&pageSize=10
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 根据id查询账户基本信息
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/account/getAccountBasicInfoById/1
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 根据id下线账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/offline/1
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 校验账户密码
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/account/verifyPassword?password=admin
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 修改账户密码
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/changePassword
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "originalPassword": "admin",
  "newPassword": "admin"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 获取在线账户数量等信息
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/account/onlineAccounts
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 根据id归档账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/archiveById/3
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 根据id从归档中恢复账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/recoverFromArchiveById/3
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 退出登录
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/logout
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}
