### 注册账户
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/register
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*

{
  "username": "test_2",
  "password": "test_2",
  "roleCodes": [
    "test",
    "admin"
  ],
  "avatarUrl": "https://github.com/users/conifercone",
  "phone": "13021705689",
  "sex": "MALE",
  "email": "547913250@qq.com",
  "timezone": "Asia/Shanghai",
  "language": "EN",
  "birthday": "1995-08-02",
  "addresses": [
    {
      "street": "历城区",
      "city": "济南市",
      "state": "山东省",
      "postalCode": "250101",
      "country": "中国"
    },
    {
      "street": "历下区",
      "city": "济南市",
      "state": "山东省",
      "postalCode": "250101",
      "country": "中国"
    }
  ],
  "captchaId": 127267766272,
  "captcha": "U4BC"
}

### 根据ID修改账户基本信息
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/updateById
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "id": 1,
  "bio": "不想把这个世界交给无趣的人"
}


### 分页获取账户（不查询总数）
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/account/findAllSlice?current=1&pageSize=10&username=admin
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 账户添加地址
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/addAddress
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "country": "中国",
  "state": "山东省",
  "city": "济南市",
  "street": "历城区",
  "postalCode": "250101"
}

### 更新账户角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/updateRoleById
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "id": 1,
  "roleCodes": [
    "admin"
  ]
}

### 重置当前账户系统设置
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/resetSystemSettingsBySettingsId/601146283917317
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 当前账户添加系统设置
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/account/addSystemSettings
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "profile": "default",
  "name": "默认系统设置",
  "enabled": true
}

### 通过设置id修改系统设置
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/account/modifySystemSettingsBySettingsId
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "id": "601146283917317",
  "name": "默认系统设置"
}
