### 流式文件上传
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("storage-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{storage-service-url}}/file/sync/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

--WebAppBoundary
Content-Disposition: form-data; name="storageAddress"
Content-Type: text/plain

test
--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

test
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: application/json

< ./assets/test.txt
--WebAppBoundary--

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 流式文件下载
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("storage-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{storage-service-url}}/file/download?storageAddress=mail&
    name=template/zh/verification_code.html&rename=verification_code.html
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 文件删除
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("storage-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
DELETE {{storage-service-url}}/file/remove
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "storageAddress": "test",
  "name": "test2.log"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### 流式文件获取字符串文件内容
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("storage-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{storage-service-url}}/file/stringContent?storageAddress=mail&
    name=template/zh/verification_code.html
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}
