### 模板邮件发送
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("mail-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{mail-service-url}}/template/send
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "address": "mail",
  "name": "template/zh/verification_code.html",
  "data": {
    "verifyCode": [
      5,
      2,
      8,
      4
    ]
  },
  "to": "kaiyu.shan@outlook.com",
  "subject": "验证码"
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}
