### 添加角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
POST {{authentication-service-url}}/role/add
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "code": "test2",
  "name": "测试",
  "permissionIds": [
    1,
    2
  ]
}

### 更新角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/role/updateById
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "id": 3,
  "name": "updated",
  "permissionIds": [
    1
  ]
}

### 查询角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/role/findAll?current=1&pageSize=10&code=admin
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 查询已归档角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/role/findArchivedAll?current=1&pageSize=10
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 查询角色(不查询总数)
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/role/findAllSlice?current=1&pageSize=10
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 查询已归档角色(不查询总数)
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/role/findArchivedAllSlice?current=1&pageSize=10
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 根据ID删除角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
DELETE {{authentication-service-url}}/role/deleteById/3
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 根据code删除角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
DELETE {{authentication-service-url}}/role/deleteByCode/test2
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 根据ID归档角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/role/archiveById/3
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 根据id从归档中恢复角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/role/recoverFromArchiveById/3
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 添加祖先角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/role/addAncestor
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

{
  "descendantId": 4,
  "ancestorId": 2
}

### 获取所有根角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/role/findRoot?current=1&pageSize=10
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 获取直系后代角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
PUT {{authentication-service-url}}/role/findDirect?current=1&pageSize=10&ancestorId=1
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 删除角色路径
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
DELETE {{authentication-service-url}}/role/deletePath?descendantId=2&ancestorId=1
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 根据id查询角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/role/findById/1
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}

### 根据code查询角色
< {%
  import {generateHeaders} from "./utils"

  const headers = generateHeaders(request.environment.get("authentication-service-url"))
  request.variables.set("signature", headers.signature)
  request.variables.set("timestamp", headers.timestamp)
  request.variables.set("requestId", headers.requestId)
%}
GET {{authentication-service-url}}/role/findByCode/admin
Content-Type: application/json
X-Request-ID: {{requestId}}
X-Signature: {{signature}}
X-Timestamp: {{timestamp}}
Connection: keep-alive
Accept: */*
Authorization: Bearer {{$auth.token("admin")}}
