apply(from = "../scripts/springboot.gradle")

dependencies {
    implementation(project(":centaur-authentication:authentication-client"))
    implementation(project(":centaur-message:message-infrastructure"))
    implementation(project(":centaur-message:message-adapter"))
    implementation(project(":centaur-message:message-client"))
    implementation(project(":centaur-message:message-application"))
    implementation(project(":centaur-extension"))
    implementation(libs.netty)
    implementation(libs.springBootDataJpa)
    implementation(libs.postgresql)
    implementation(libs.consulDiscovery)
    implementation(libs.consulConfig)
    implementation(libs.bundles.micrometer)
    implementation(libs.grpcSpringBootStarter)
    testImplementation(libs.springbootTest)
    testImplementation(libs.jasypt)
    testImplementation(libs.springSecurityTest)
    testImplementation(libs.grpcClientSpringBootStarter)
    testImplementation(libs.springWeb)
    implementation(libs.jasypt)
    implementation(libs.swagger3Ui)
    implementation(libs.flywayCore)
    implementation(libs.flywayDatabasePostgresql)
    implementation(libs.hibernateTypes63)
    implementation(libs.redisOmSpring)
    implementation(libs.jobrunrSpringBoot3Starter)
    annotationProcessor(libs.redisOmSpring)
}
