:doctype: article
:imagesdir: ..
:icons: font

- link:CODE_OF_CONDUCT.zh_CN.adoc[简体中文]
- link:CODE_OF_CONDUCT.zh_TW.adoc[繁體中文]
- link:../CODE_OF_CONDUCT.adoc[English]
- link:CODE_OF_CONDUCT.ja.adoc[日本語]
- link:CODE_OF_CONDUCT.ko.adoc[한국어]

== 貢獻者誓言行為規範

=== 目次

- <<our-pledge, 我們的承諾>>
- <<our-standards, 我們的標準>>
- <<enforcement-responsibilities, 執行責任>>
- <<scope, 適用範圍>>
- <<enforcement, 執行>>
- <<enforcement-guidelines, 執行指南>>
- <<attribution, 歸屬>>

[#our-pledge]
== 我們的承諾

作為成員、貢獻者和領導者，我們承諾讓每個人在我們的社群中參與時都不會受到騷擾，不論其年齡、身體尺寸、顯性或隱性的殘疾、種族、性別特徵、性別認同和表達、經驗水平、教育背景、社會經濟地位、國籍、外貌、種族、宗教或性取向。

我們承諾以有助於建立開放、歡迎、多元、包容和健康的社群的方式行事和互動。

[#our-standards]
== 我們的標準

有助於我們社群積極環境的行為示例包括：

- 對他人表現出同情和善意
- 尊重不同的觀點、看法和經驗
- 提供並優雅地接受建設性的反饋
- 對因我們的錯誤而受影響的人負責並道歉，並從中學習
- 專注於整體社群的最佳利益，而非僅考慮個人利益

不可接受的行為示例包括：

- 使用性暗示的語言或圖片，以及任何形式的性騷擾或冒犯
- 噴人、侮辱性或貶損性的評論，以及個人或政治攻擊
- 公開或私下的騷擾
- 未經明確允許下公開他人的私人信息，例如地址或電子郵件
- 其他在專業環境中合理認為不適當的行為

[#enforcement-responsibilities]
== 執行責任

社群領導者負責明確和執行我們的行為標準，並對任何他們認為不適當、威脅、冒犯或有害的行為採取適當和公平的糾正措施。

社群領導者有權且有責任刪除、編輯或拒絕評論、提交、代碼、維基編輯、問題和其他不符合本行為規範的貢獻，並在適當時解釋審查決定的理由。

[#scope]
== 適用範圍

本行為規範適用於所有社群空間，也適用於個人在公共空間中代表社群的情況。代表我們社群的示例包括使用官方電子郵件地址、通過官方社交媒體帳戶發佈內容，或作為指定代表出席線上或線下活動。

[#enforcement]
== 執行

可以將虐待、騷擾或其他不可接受的行為向社群領導者舉報，聯繫方式為 mailto:kaiyu.shan@outlook.com[kaiyu.shan@outlook.com]。所有投訴將被迅速和公平地審查和調查。

所有社群領導者有義務尊重事件舉報者的隱私和安全。

[#enforcement-guidelines]
== 執行指南

社群領導者將在確認違反本行為規範後，根據以下社群影響指南決定後果：

[#correction]
=== 1. 更正

**社群影響**：使用不當語言或其他被認為不專業或不受歡迎的行為。

**後果**：社群領導者將發出私人書面警告，明確違規行為的性質，並解釋為何該行為不適當。可能要求公開道歉。

[#warning]
=== 2. 警告

**社群影響**：通過單次事件或一系列行為的違規。

**後果**：警告並附帶持續行為的後果。在指定的時間內，禁止與相關人員的互動，包括與執行行為規範的人進行的非請求互動。這包括避免在社群空間及社交媒體等外部渠道的互動。違反這些條款可能導致臨時或永久禁令。

[#temporary-ban]
=== 3. 臨時禁令

**社群影響**：嚴重違反社群標準，包括持續的不當行為。

**後果**：在指定的時間內禁止與社群的任何互動或公開溝通。此期間內，禁止與相關人員的任何公開或私人互動，包括與執行行為規範的人進行的非請求互動。違反這些條款可能導致永久禁令。

[#permanent-ban]
=== 4. 永久禁令

**社群影響**：表現出違反社群標準的模式，包括持續的不當行為、騷擾個人，或對某些群體進行攻擊或貶低。

**後果**：永久禁止在社群內的任何公開互動。

[#attribution]
== 歸屬

本行為規範改編自 link:https://www.contributor-covenant.org[貢獻者誓言]，版本 2.0，訪問 link:https://www.contributor-covenant.org/version/2/0/code_of_conduct.html[https://www.contributor-covenant.org/version/2/0/code_of_conduct.html]。

社群影響指南的靈感來源於 link:https://github.com/mozilla/diversity[Mozilla 的行為規範執行階梯]。

有關本行為規範的常見問題解答，請參見 FAQ link:https://www.contributor-covenant.org/faq[https://www.contributor-covenant.org/faq]。翻譯版本可在 link:https://www.contributor-covenant.org/translations[https://www.contributor-covenant.org/translations] 獲得。
