#file: noinspection UndefinedAction,UndefinedParamsPresent

name: Dependency Submission

on:
  push:
    paths:
      - '**/build.gradle.kts'
      - 'gradle/libs.versions.toml'
      - 'buildSrc/gradle/libs.versions.toml'
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    env:
      MUMU_SIGNING_KEY_ID: ${{ secrets.MUMU_SIGNING_KEY_ID }}
      MUMU_SIGNING_KEY_CONTENT: ${{ secrets.MUMU_SIGNING_KEY_CONTENT }}
      MUMU_SIGNING_PASSWORD: ${{ secrets.MUMU_SIGNING_PASSWORD }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
